// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MonitorConfGetterClient is the client API for MonitorConfGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorConfGetterClient interface {
	GetConf(ctx context.Context, in *MonitorConfRequest, opts ...grpc.CallOption) (*MonitorConfResponse, error)
}

type monitorConfGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorConfGetterClient(cc grpc.ClientConnInterface) MonitorConfGetterClient {
	return &monitorConfGetterClient{cc}
}

func (c *monitorConfGetterClient) GetConf(ctx context.Context, in *MonitorConfRequest, opts ...grpc.CallOption) (*MonitorConfResponse, error) {
	out := new(MonitorConfResponse)
	err := c.cc.Invoke(ctx, "/rpc.MonitorConfGetter/GetConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorConfGetterServer is the server API for MonitorConfGetter service.
// All implementations must embed UnimplementedMonitorConfGetterServer
// for forward compatibility
type MonitorConfGetterServer interface {
	GetConf(context.Context, *MonitorConfRequest) (*MonitorConfResponse, error)
	mustEmbedUnimplementedMonitorConfGetterServer()
}

// UnimplementedMonitorConfGetterServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorConfGetterServer struct {
}

func (*UnimplementedMonitorConfGetterServer) GetConf(context.Context, *MonitorConfRequest) (*MonitorConfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConf not implemented")
}
func (*UnimplementedMonitorConfGetterServer) mustEmbedUnimplementedMonitorConfGetterServer() {}

func RegisterMonitorConfGetterServer(s *grpc.Server, srv MonitorConfGetterServer) {
	s.RegisterService(&_MonitorConfGetter_serviceDesc, srv)
}

func _MonitorConfGetter_GetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorConfGetterServer).GetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MonitorConfGetter/GetConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorConfGetterServer).GetConf(ctx, req.(*MonitorConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorConfGetter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MonitorConfGetter",
	HandlerType: (*MonitorConfGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConf",
			Handler:    _MonitorConfGetter_GetConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/proto/task.proto",
}

// ProcessEventClient is the client API for ProcessEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessEventClient interface {
	ProcessEventHandler(ctx context.Context, in *ProcessEventRequest, opts ...grpc.CallOption) (*ProcessEventResponse, error)
}

type processEventClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessEventClient(cc grpc.ClientConnInterface) ProcessEventClient {
	return &processEventClient{cc}
}

func (c *processEventClient) ProcessEventHandler(ctx context.Context, in *ProcessEventRequest, opts ...grpc.CallOption) (*ProcessEventResponse, error) {
	out := new(ProcessEventResponse)
	err := c.cc.Invoke(ctx, "/rpc.ProcessEvent/ProcessEventHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessEventServer is the server API for ProcessEvent service.
// All implementations must embed UnimplementedProcessEventServer
// for forward compatibility
type ProcessEventServer interface {
	ProcessEventHandler(context.Context, *ProcessEventRequest) (*ProcessEventResponse, error)
	mustEmbedUnimplementedProcessEventServer()
}

// UnimplementedProcessEventServer must be embedded to have forward compatible implementations.
type UnimplementedProcessEventServer struct {
}

func (*UnimplementedProcessEventServer) ProcessEventHandler(context.Context, *ProcessEventRequest) (*ProcessEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessEventHandler not implemented")
}
func (*UnimplementedProcessEventServer) mustEmbedUnimplementedProcessEventServer() {}

func RegisterProcessEventServer(s *grpc.Server, srv ProcessEventServer) {
	s.RegisterService(&_ProcessEvent_serviceDesc, srv)
}

func _ProcessEvent_ProcessEventHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessEventServer).ProcessEventHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ProcessEvent/ProcessEventHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessEventServer).ProcessEventHandler(ctx, req.(*ProcessEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProcessEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ProcessEvent",
	HandlerType: (*ProcessEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessEventHandler",
			Handler:    _ProcessEvent_ProcessEventHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/proto/task.proto",
}
